services:
  storybook:
    build: 
      context: ./
      args:
        GIT_USER_NAME: "${GIT_USER_NAME}"
        GIT_USER_EMAIL: "${GIT_USER_EMAIL}"
    env_file:
      - .env
    container_name: storybook
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
     - 6006:6006
    environment:
      NODE_ENV: development
    command: ["npm", "run", "storybook"]